/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-24 05:39:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\" />\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("        <meta name=\"description\" content=\"\" />\n");
      out.write("        <meta name=\"author\" content=\"\" />\n");
      out.write("        <title>Clean Blog - Start Bootstrap Theme</title>\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\n");
      out.write("        <!-- Font Awesome icons (free version)-->\n");
      out.write("        <script src=\"https://use.fontawesome.com/releases/v6.1.0/js/all.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <!-- Google fonts-->\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\n");
      out.write("        <link href=\"css/styles.css\" rel=\"stylesheet\" />\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <!-- Navigation-->\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light\" id=\"mainNav\">\n");
      out.write("            <div class=\"container px-4 px-lg-5\">\n");
      out.write("                <a class=\"navbar-brand\" href=\"index.jsp\">\n");
      out.write('\n');
      out.write("\n");
      out.write("                    ");
      out.print(request.getParameter("home"));
      out.write(" Bootstrap ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                </a>\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("                    Menu\n");
      out.write("                    <i class=\"fas fa-bars\"></i>\n");
      out.write("                </button>\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\n");
      out.write("                    <ul class=\"navbar-nav ms-auto py-4 py-lg-0\">\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link px-lg-3 py-3 py-lg-4\" href=\"index.jsp\">Home</a></li>\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link px-lg-3 py-3 py-lg-4\" href=\"about.html\">About</a></li>\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link px-lg-3 py-3 py-lg-4\" href=\"post.html\">Sample Post</a></li>\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link px-lg-3 py-3 py-lg-4\" href=\"contact.jsp\">Contact</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <!-- Page Header-->\n");
      out.write("        <header class=\"masthead\" style=\"background-image: url('assets/img/home-bg.jpg')\">\n");
      out.write("            <div class=\"container position-relative px-4 px-lg-5\">\n");
      out.write("                <div class=\"row gx-4 gx-lg-5 justify-content-center\">\n");
      out.write("                    <div class=\"col-md-10 col-lg-8 col-xl-7\">\n");
      out.write("                        <div class=\"site-heading\">\n");
      out.write("                            <h1>");
      out.print(request.getParameter("param"));
      out.write(" Blog</h1>\n");
      out.write("                            <span class=\"subheading\">A Blog Theme by Start Bootstrap</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("        <!-- Main Content-->\n");
      out.write("        <div class=\"container px-4 px-lg-5\">\n");
      out.write("            <div class=\"row gx-4 gx-lg-5 justify-content-center\">\n");
      out.write("                <div class=\"col-md-10 col-lg-8 col-xl-7\">\n");
      out.write("                    <!-- Post preview-->\n");
      out.write("                    <div class=\"post-preview\">\n");
      out.write("                        <a href=\"post.html\">\n");
      out.write("                            <h2 class=\"post-title\">Man must explore, and this is exploration at its greatest</h2>\n");
      out.write("                            <h3 class=\"post-subtitle\">Problems look mighty small from 150 miles up</h3>\n");
      out.write("                        </a>\n");
      out.write("                        <p class=\"post-meta\">\n");
      out.write("                            Posted by\n");
      out.write("                            <a href=\"#!\">Start Bootstrap</a>\n");
      out.write("                            on September 24, 2022\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Divider-->\n");
      out.write("                    <hr class=\"my-4\" />\n");
      out.write("                    <!-- Post preview-->\n");
      out.write("                    <div class=\"post-preview\">\n");
      out.write("                        <a href=\"post.html\"><h2 class=\"post-title\">I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.</h2></a>\n");
      out.write("                        <p class=\"post-meta\">\n");
      out.write("                            Posted by\n");
      out.write("                            <a href=\"#!\">Start Bootstrap</a>\n");
      out.write("                            on September 18, 2022\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Divider-->\n");
      out.write("                    <hr class=\"my-4\" />\n");
      out.write("                    <!-- Post preview-->\n");
      out.write("                    <div class=\"post-preview\">\n");
      out.write("                        <a href=\"post.html\">\n");
      out.write("                            <h2 class=\"post-title\">Science has not yet mastered prophecy</h2>\n");
      out.write("                            <h3 class=\"post-subtitle\">We predict too much for the next year and yet far too little for the next ten.</h3>\n");
      out.write("                        </a>\n");
      out.write("                        <p class=\"post-meta\">\n");
      out.write("                            Posted by\n");
      out.write("                            <a href=\"#!\">Start Bootstrap</a>\n");
      out.write("                            on August 24, 2022\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Divider-->\n");
      out.write("                    <hr class=\"my-4\" />\n");
      out.write("                    <!-- Post preview-->\n");
      out.write("                    <div class=\"post-preview\">\n");
      out.write("                        <a href=\"post.html\">\n");
      out.write("                            <h2 class=\"post-title\">Failure is not an option</h2>\n");
      out.write("                            <h3 class=\"post-subtitle\">Many say exploration is part of our destiny, but it’s actually our duty to future generations.</h3>\n");
      out.write("                        </a>\n");
      out.write("                        <p class=\"post-meta\">\n");
      out.write("                            Posted by\n");
      out.write("                            <a href=\"#!\">Start Bootstrap</a>\n");
      out.write("                            on July 8, 2022\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Divider-->\n");
      out.write("                    <hr class=\"my-4\" />\n");
      out.write("                    <!-- Pager-->\n");
      out.write("                    <div class=\"d-flex justify-content-end mb-4\"><a class=\"btn btn-primary text-uppercase\" href=\"#!\">Older Posts →</a></div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Footer-->\n");
      out.write("        <footer class=\"border-top\">\n");
      out.write("            <div class=\"container px-4 px-lg-5\">\n");
      out.write("                <div class=\"row gx-4 gx-lg-5 justify-content-center\">\n");
      out.write("                    <div class=\"col-md-10 col-lg-8 col-xl-7\">\n");
      out.write("                        <ul class=\"list-inline text-center\">\n");
      out.write("                            <li class=\"list-inline-item\">\n");
      out.write("                                <a href=\"#!\">\n");
      out.write("                                    <span class=\"fa-stack fa-lg\">\n");
      out.write("                                        <i class=\"fas fa-circle fa-stack-2x\"></i>\n");
      out.write("                                        <i class=\"fab fa-twitter fa-stack-1x fa-inverse\"></i>\n");
      out.write("                                    </span>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"list-inline-item\">\n");
      out.write("                                <a href=\"#!\">\n");
      out.write("                                    <span class=\"fa-stack fa-lg\">\n");
      out.write("                                        <i class=\"fas fa-circle fa-stack-2x\"></i>\n");
      out.write("                                        <i class=\"fab fa-facebook-f fa-stack-1x fa-inverse\"></i>\n");
      out.write("                                    </span>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"list-inline-item\">\n");
      out.write("                                <a href=\"#!\">\n");
      out.write("                                    <span class=\"fa-stack fa-lg\">\n");
      out.write("                                        <i class=\"fas fa-circle fa-stack-2x\"></i>\n");
      out.write("                                        <i class=\"fab fa-github fa-stack-1x fa-inverse\"></i>\n");
      out.write("                                    </span>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                        <div class=\"small text-center text-muted fst-italic\">Copyright &copy; Your Website 2022</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("        <!-- Bootstrap core JS-->\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("        <!-- Core theme JS-->\n");
      out.write("        <script src=\"js/scripts.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
